spring:
  application:
    name: taskplanner
    #logging.level.org.springframework=DEBUG

  # Database connection
  datasource:
    url: jdbc:postgresql://localhost:5432/task-planner
    username: postgres
    password: postgres

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgresPlusDialect

  # Security Configuration for demonstration purpose
  # Make sure you don't pass secret key here
  app:
    jwtSecret: mySecretKey123456789012345678901234567890
    jwtExpirationMs: 86400000 # 24 hours
    jwtRefreshExpirationMs: 604800000 # 7 days
