spring:
  application:
    name: taskplanner

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task-planner}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  logging:
#    level:
#      org.springframework: INFO
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  app:
    jwtSecret: ${JWT_SECRET:diccxFxb7GQABoDcN0EmqGvjMr6SBpAUfM7Lt+AdscE=}
    jwtExpirationMs: 86400000 # 24 hours
    jwtRefreshExpirationMs: 604800000 # 7 days

  management:
    endpoints:
      web:
        base-path: /actuator
        exposure:
          include: health, metrics, prometheus
    endpoint:
      health:
        show-details: always