spring:
  application:
    name: taskplanner
    #logging.level.org.springframework=DEBUG

    # Database connection
  datasource:
    url: jdbc:postgresql://localhost:5432/task-planner
    username: postgres
    password: postgres

    # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgresPlusDialect